In [1]:
from datetime import date
import pandas as pd
import numpy as np
from nsepy import get_history

In [2]:
data=get_history('SBIN',date(2017,1,1),date(2022,12,31))
print(data)

           Symbol Series  Prev Close    Open    High     Low    Last   Close  \
Date
2017-01-02   SBIN     EQ      250.20  252.50  253.65  242.60  243.55  243.60
2017-01-03   SBIN     EQ      243.60  244.00  246.40  241.10  244.90  244.90
2017-01-04   SBIN     EQ      244.90  245.80  246.40  242.20  243.20  242.90
2017-01-05   SBIN     EQ      242.90  245.00  245.90  243.70  245.50  245.35
2017-01-06   SBIN     EQ      245.35  246.00  249.00  245.50  246.05  245.90
...           ...    ...         ...     ...     ...     ...     ...     ...
2022-12-26   SBIN     EQ      574.00  574.00  601.70  570.70  597.10  597.10
2022-12-27   SBIN     EQ      597.10  600.40  603.10  593.30  602.00  601.90
2022-12-28   SBIN     EQ      601.90  600.90  607.00  598.55  601.00  601.05
2022-12-29   SBIN     EQ      601.05  600.00  618.00  597.15  614.05  611.80
2022-12-30   SBIN     EQ      611.80  615.25  620.55  611.35  614.25  613.70

              VWAP    Volume      Turnover  Trades  Deliverable Volume  \
Date
2017-01-02  244.80  25988990  6.362168e+14  164268            12078409
2017-01-03  244.54  15963085  3.903556e+14  112537             4370526
2017-01-04  243.96  11225978  2.738651e+14   91672             3632352
2017-01-05  244.94  11970913  2.932209e+14   88254             4511456
2017-01-06  247.10  12354302  3.052714e+14   75839             3393716
...            ...       ...           ...     ...                 ...
2022-12-26  589.64  13201587  7.784134e+14  210003             4497406
2022-12-27  598.21   9638618  5.765913e+14  206219             2569120
2022-12-28  602.94   7988631  4.816651e+14  143945             2562261
2022-12-29  608.16  20130392  1.224252e+15  168187            11439937
2022-12-30  615.43  13052895  8.033100e+14  158347             6160516

            %Deliverble
Date
2017-01-02       0.4648
2017-01-03       0.2738
2017-01-04       0.3236
2017-01-05       0.3769
2017-01-06       0.2747
...                 ...
2022-12-26       0.3407
2022-12-27       0.2665
2022-12-28       0.3207
2022-12-29       0.5683
2022-12-30       0.4720

[1487 rows x 14 columns]

In [3]:
data.to_csv('SBI.csv')

In [4]:
data

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2017-01-02,SBIN,EQ,250.20,252.50,253.65,242.60,243.55,243.60,244.80,25988990,6.362168e+14,164268,12078409,0.4648
2017-01-03,SBIN,EQ,243.60,244.00,246.40,241.10,244.90,244.90,244.54,15963085,3.903556e+14,112537,4370526,0.2738
2017-01-04,SBIN,EQ,244.90,245.80,246.40,242.20,243.20,242.90,243.96,11225978,2.738651e+14,91672,3632352,0.3236
2017-01-05,SBIN,EQ,242.90,245.00,245.90,243.70,245.50,245.35,244.94,11970913,2.932209e+14,88254,4511456,0.3769
2017-01-06,SBIN,EQ,245.35,246.00,249.00,245.50,246.05,245.90,247.10,12354302,3.052714e+14,75839,3393716,0.2747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-26,SBIN,EQ,574.00,574.00,601.70,570.70,597.10,597.10,589.64,13201587,7.784134e+14,210003,4497406,0.3407
2022-12-27,SBIN,EQ,597.10,600.40,603.10,593.30,602.00,601.90,598.21,9638618,5.765913e+14,206219,2569120,0.2665
2022-12-28,SBIN,EQ,601.90,600.90,607.00,598.55,601.00,601.05,602.94,7988631,4.816651e+14,143945,2562261,0.3207
2022-12-29,SBIN,EQ,601.05,600.00,618.00,597.15,614.05,611.80,608.16,20130392,1.224252e+15,168187,11439937,0.5683
2022-12-30,SBIN,EQ,611.80,615.25,620.55,611.35,614.25,613.70,615.43,13052895,8.033100e+14,158347,6160516,0.4720

In [5]:
data

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2017-01-02,SBIN,EQ,250.20,252.50,253.65,242.60,243.55,243.60,244.80,25988990,6.362168e+14,164268,12078409,0.4648
2017-01-03,SBIN,EQ,243.60,244.00,246.40,241.10,244.90,244.90,244.54,15963085,3.903556e+14,112537,4370526,0.2738
2017-01-04,SBIN,EQ,244.90,245.80,246.40,242.20,243.20,242.90,243.96,11225978,2.738651e+14,91672,3632352,0.3236
2017-01-05,SBIN,EQ,242.90,245.00,245.90,243.70,245.50,245.35,244.94,11970913,2.932209e+14,88254,4511456,0.3769
2017-01-06,SBIN,EQ,245.35,246.00,249.00,245.50,246.05,245.90,247.10,12354302,3.052714e+14,75839,3393716,0.2747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-26,SBIN,EQ,574.00,574.00,601.70,570.70,597.10,597.10,589.64,13201587,7.784134e+14,210003,4497406,0.3407
2022-12-27,SBIN,EQ,597.10,600.40,603.10,593.30,602.00,601.90,598.21,9638618,5.765913e+14,206219,2569120,0.2665
2022-12-28,SBIN,EQ,601.90,600.90,607.00,598.55,601.00,601.05,602.94,7988631,4.816651e+14,143945,2562261,0.3207
2022-12-29,SBIN,EQ,601.05,600.00,618.00,597.15,614.05,611.80,608.16,20130392,1.224252e+15,168187,11439937,0.5683
2022-12-30,SBIN,EQ,611.80,615.25,620.55,611.35,614.25,613.70,615.43,13052895,8.033100e+14,158347,6160516,0.4720